spring:
  main:
    banner-mode: off

  datasource:
    url: jdbc:h2:mem:zonas_db;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.H2Dialect

server:
  port: 8080

debug: false

logging:
  level:
    root: error
    org.hibernate: error
    org.hibernate.SQL: off
    org.hibernate.orm.jdbc.bind: off
    org.springframework: error
    org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLogger: off
    com.zaxxer.hikari: error
    ec.edu.espe.zonas: error
